### ISSUE TITLE
Kanban Board Setup

### ISSUE THREAD

**Issue by dodoburner** [Owusu-Desmond/space-travelers#24]
Here is the [link](https://github.com/Owusu-Desmond/space-travelers/projects/1) to our project. 
We are a team of two, Desmond Owusu and Dorian Urem.
Would you kindly review if we setup everything correctly.

**Comment by TedLivist** [comment]
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @dodoburner and @Owusu-Desmond,

Good job so far!
✔️ Kanban board columns are complete
✔️ All tasks are assigned
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Your number of tasks should be 17 but it is 16 because you are missing this task from the template. Ensure it is added:

  ![display-m](https://user-images.githubusercontent.com/36542986/185882313-3f575efc-cdd3-49db-90bd-35bb11b18303.jpg)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by dodoburner** [comment]
@TedLivist Thank you for your observations, I have added the missing issue.

**Comment by rloterh** [comment]
## Status: Approved :heavy_check_mark:

Hi Team,  

Your project is complete! 🍾🚢 Congratulations!  🎉💯🌟 

## Highlights 👍
- Board has required number of tasks

<br>
Keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
